# Generated by Django 5.1.3 on 2024-12-01 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance in kilometers')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('ev', 'Electric Vehicle')], max_length=20)),
                ('num_riders', models.IntegerField(default=1, help_text='Number of passengers')),
                ('traffic_condition', models.CharField(choices=[('light', 'Light Traffic'), ('moderate', 'Moderate Traffic'), ('heavy', 'Heavy Traffic')], max_length=20)),
                ('idle_time', models.IntegerField(default=0, help_text='Idle time in minutes')),
                ('ride_time', models.DateTimeField(auto_now_add=True)),
                ('co2_emissions', models.FloatField(blank=True, null=True)),
                ('co2_savings', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rides', models.IntegerField(default=0)),
                ('total_co2_saved', models.FloatField(default=0)),
                ('total_distance', models.FloatField(default=0)),
                ('preferred_vehicle_type', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
